version: 2

multi-ecosystem-groups:
  dependencies:
    assignees:
      - BrailleBennett
    schedule:
      interval: weekly
      day: sunday

updates:
  - package-ecosystem: maven
      directory: "/"
      patterns: [ "*" ]
      multi-ecosystem-group: dependencies

  - package-ecosystem: nix
    directory: "/"
    patterns: [ "*" ]
    multi-ecosystem-group: dependencies
